### PR TITLE
Exclusions: Implement default exclusion system

### LINKED ISSUE #618: Default App Exceptions (Similar in SD Maid 1)
for the following apps you should include non-deletable app exceptions for security purposes similar in SD Maid 1.

`com.starfinanz.mobile.android.pushtan`
Here you lose the device registration and have to request a new QR code from the bank (via postal service or in branch) and re-register the device - very bad!

`de.zollsoft.impfapp`
Here you lose the deposited COVID vaccination certificates, you have to delete all of them and scan them again - not bad but not nice either.

This list is not complete, you can expand it if necessary.

Pixel 7
Andoid 13 (Patches last of August 2023)
not rooted!
SD-Maid 0.11.0-beta0

### PR DESCRIPTION
**Pull request by d4rken**
Clicking a default exclusion will open the GitHub ticket that caused it to be added.

Closes #618

Screenshot from 2023-12-04 12-02-33

### CODE REVIEW

**Review by julywint — COMMENTED** [review]
app/src/main/java/eu/darken/sdmse/exclusion/core/DefaultExclusions.kt

**Comment by azergovany98** [comment]
good thanks

**Review by ZAVGA — COMMENTED** [review]
app/src/main/java/eu/darken/sdmse/exclusion/core/DefaultExclusions.kt

**Review by schlusel — COMMENTED** [review]
**Merci**

**Review by schlusel — APPROVED** [review]

**Review by dp88workinfo — APPROVED** [review]

**Pull request merged**
