### PR TITLE
AppCleaner: Don't return to app when using accessibility functions via scheduler

### PR DESCRIPTION
**Pull request by d4rken**
If automation is used from the background (scheduler or a future widget), don't return to the main app after operations are finished. Previously this was also the case, but due to going back by "back button", it wasn't that visible.

### CODE REVIEW

**Comment by MarkyMarkDE** [comment]
Unfortunately is this bug not fixed in 1.0, exactly the same behavior as before 🤷

**Comment by d4rken** [comment]
So it still returns to SD Maid? Or is the bug that the last system details window stays open?

You don't need to reinstall, I don't think any of this is fixed by a re-install.

**Comment by MarkyMarkDE** [comment]
> So it still returns to SD Maid? Or is the bug that the last system details window stays open?
> 
> You don't need to reinstall, I don't think any of this is fixed by a re-install.

SDMaid isn't open (visible) the scheduler open the overlay (normally result) and do his job, after that SDMaid overlay is being closed but the ui is open now, but why? This is exact before v1.0 and right, uninstall usw. didn't change anything

**Comment by d4rken** [comment]
> "the ui is open"

The UI of the system or the UI of SD Maid?

**Comment by MarkyMarkDE** [comment]
Mean the UI of SDMaid. Other try: SDMaid UI is not open, the schedule 
starts and the progress overlay is showing (correct) and if the schedule 
job is finished, the progress overlay will be close (correct) but the you 
see the open SDMaid UI and this behavior is not as designed or?



Am 31. Mai 2024 09:20:57 schrieb Matthias Urhahn ***@***.***>:

**Comment by d4rken** [comment]
Yea that is not correct. If SD Maid is not open when the schedule starts, it shouldn't be open afterwards. Opened this ticket to track it: #1197

**Pull request merged**
